version: '3.9'

services:
  database:
    image: mysql:latest
    container_name: database
    ports:
      - 13306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=films
