name: Discord Notification

on:
  push:
    branches:
      - "main"  # Substitua pela sua branch principal

jobs:
  notify-discord:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Notify Discord
      uses: ad-m/discord-send-message@v0.4.0
      with:
        webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
        webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
        message: "New push to main branch! Commit by ${{ github.actor }}"
